version: "3.9"

services:
  contractus:
    image: contractus:dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        GO_VERSION: ${GO_VERSION}
        GOLANGCI_LINT_VERSION: ${GOLANGCI_LINT_VERSION}
    environment:
      CONTRACTUS_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/contractus?sslmode=disable
      CONTRACTUS_GOOGLE_REDIRECT_URL: http://localhost:8080/callback
      CONTRACTUS_JWT_SECRET_KEY: secret
      CONTRACTUS_ACCESS_TYPE: offline
    volumes:
      - .:/app/src
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    command: go run ./cmd/contractus
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: contractus
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 3s
      retries: 5
volumes:
  db:
