ARG GO_VERSION
FROM golang:${GO_VERSION}-bullseye

RUN apt-get update && \
    apt-get install -y git

ARG GOLANGCI_LINT_VERSION

RUN go install github.com/golangci/golangci-lint/cmd/golangci-lint@${GOLANGCI_LINT_VERSION}

# https://stackoverflow.com/questions/72292278/error-obtaining-vcs-status-when-running-delve-as-root
# Similar error. Inside the container we don't have .git, for this reason we need to configure it
RUN git config --global --add safe.directory /app/src
WORKDIR /app/src

COPY go.mod go.sum ./
RUN go mod download

COPY . .
